export const contacts = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice.j@examplecorp.com",
    company: "ExampleCorp",
    title: "Marketing Director",
    status: "Contacted",
    lastContacted: "2024-05-20",
  },
  {
    id: "2",
    name: "Bob Williams",
    email: "bob.w@innovatech.io",
    company: "Innovatech",
    title: "Head of Sales",
    status: "Replied",
    lastContacted: "2024-05-22",
  },
  {
    id: "3",
    name: "Charlie Brown",
    email: "charlie@datastream.co",
    company: "DataStream",
    title: "CEO",
    status: "Not Contacted",
    lastContacted: null,
  },
  {
    id: "4",
    name: "Diana Prince",
    email: "diana.p@solutioninc.com",
    company: "SolutionInc",
    title: "VP of Engineering",
    status: "Meeting Scheduled",
    lastContacted: "2024-05-18",
  },
  {
    id: "5",
    name: "Ethan Hunt",
    email: "ethan.h@globex.net",
    company: "Globex",
    title: "Senior Developer",
    status: "Contacted",
    lastContacted: "2024-05-21",
  },
  {
    id: "6",
    name: "Fiona Glenanne",
    email: "fiona@synergy.ai",
    company: "Synergy AI",
    title: "Product Manager",
    status: "Replied",
    lastContacted: "2024-05-23",
  },
];

export const analyticsData = [
  { date: "Jan", sent: 400, opened: 240, replied: 40, meetings: 5 },
  { date: "Feb", sent: 300, opened: 139, replied: 30, meetings: 3 },
  { date: "Mar", sent: 500, opened: 380, replied: 80, meetings: 10 },
  { date: "Apr", sent: 478, opened: 290, replied: 70, meetings: 8 },
  { date: "May", sent: 689, opened: 480, replied: 120, meetings: 15 },
  { date: "Jun", sent: 539, opened: 380, replied: 90, meetings: 12 },
];
